# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Network Security Ninja
email: jbess@duck.com
description: >- # this means to ignore newlines until "baseurl:"
    A blog to post my Tactics, Techniques, and Procedures (TTPs) as a card-carrying member of the Blue Team (Cyber Defense). 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true
author: Jeremiah Bess
linkedin_username: jeremiahbess
twitter_username: netsecninja
mastodon:
  - username: netsecninja
    instance: infosec.exchange
github_username:  netsecninja
google_analytics: UA-922167-7

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-hacker
#theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# Collections:
collections:
  dfir-notes:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
